// 시티 도미니언 대본 96줄. voice/city-dominion/annotation.csv에서 옮김 (tests/lines.test.js가 같은지 확인).
(function (root) {
  "use strict";
  const LINES = [
    {"id":"001","key":"welcome","scene":"시작 · 친구 초대","dir":"따뜻하게","text":"시티 도미니언에 온 걸 환영해!"},
    {"id":"002","key":"adventure_start","scene":"시작 · 친구 초대","dir":"설레게","text":"우리만의 도시 여행, 시작해 볼까?"},
    {"id":"003","key":"room_created","scene":"시작 · 친구 초대","dir":"친근하게","text":"방이 만들어졌어! 친구들을 초대해 줘."},
    {"id":"004","key":"player_joined","scene":"시작 · 친구 초대","dir":"반갑게","text":"새로운 친구가 도착했어!"},
    {"id":"005","key":"waiting_friends","scene":"시작 · 친구 초대","dir":"편안하게","text":"친구들을 기다리고 있어."},
    {"id":"006","key":"party_ready","scene":"시작 · 친구 초대","dir":"활기차게","text":"모두 준비됐어? 함께 출발하자!"},
    {"id":"007","key":"game_start","scene":"시작 · 친구 초대","dir":"힘 있게","text":"주사위 하나로 시작되는 도시 모험!"},
    {"id":"008","key":"my_turn_01","scene":"내 턴 · 주사위","dir":"경쾌하게","text":"내 차례야!"},
    {"id":"009","key":"my_turn_02","scene":"내 턴 · 주사위","dir":"기대하며","text":"자, 이번엔 어디로 갈까?"},
    {"id":"010","key":"my_turn_03","scene":"내 턴 · 주사위","dir":"응원하며","text":"멋진 한 수를 보여 줘!"},
    {"id":"011","key":"choose_tactic","scene":"내 턴 · 주사위","dir":"또렷하게","text":"이번 차례의 작전을 골라 줘!"},
    {"id":"012","key":"roll_ready","scene":"내 턴 · 주사위","dir":"유쾌하게","text":"준비됐으면 주사위를 굴려 줘!"},
    {"id":"013","key":"dice_air","scene":"내 턴 · 주사위","dir":"상승감 있게","text":"높이 날아라, 주사위!"},
    {"id":"014","key":"dice_tumble","scene":"내 턴 · 주사위","dir":"장난스럽게","text":"데굴데굴! 어디에 멈출까?"},
    {"id":"015","key":"dice_land","scene":"내 턴 · 주사위","dir":"명확하게","text":"착지! 숫자를 확인해 봐!"},
    {"id":"016","key":"double_01","scene":"내 턴 · 주사위","dir":"신나게","text":"더블! 한 번 더 굴릴 수 있어!"},
    {"id":"017","key":"double_02","scene":"내 턴 · 주사위","dir":"놀라며","text":"또 더블이야! 행운이 따라오네!"},
    {"id":"018","key":"turn_end","scene":"내 턴 · 주사위","dir":"산뜻하게","text":"좋아! 다음 친구의 차례야."},
    {"id":"019","key":"dice_face_1","scene":"주사위 숫자 — 각각 따로 녹음","dir":"또렷하고 경쾌하게","text":"하나!"},
    {"id":"020","key":"dice_face_2","scene":"주사위 숫자 — 각각 따로 녹음","dir":"또렷하고 경쾌하게","text":"둘!"},
    {"id":"021","key":"dice_face_3","scene":"주사위 숫자 — 각각 따로 녹음","dir":"또렷하고 경쾌하게","text":"셋!"},
    {"id":"022","key":"dice_face_4","scene":"주사위 숫자 — 각각 따로 녹음","dir":"또렷하고 경쾌하게","text":"넷!"},
    {"id":"023","key":"dice_face_5","scene":"주사위 숫자 — 각각 따로 녹음","dir":"또렷하고 경쾌하게","text":"다섯!"},
    {"id":"024","key":"dice_face_6","scene":"주사위 숫자 — 각각 따로 녹음","dir":"또렷하고 경쾌하게","text":"여섯!"},
    {"id":"025","key":"dice_total_2","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 두 칸!"},
    {"id":"026","key":"dice_total_3","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 세 칸!"},
    {"id":"027","key":"dice_total_4","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 네 칸!"},
    {"id":"028","key":"dice_total_5","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 다섯 칸!"},
    {"id":"029","key":"dice_total_6","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 여섯 칸!"},
    {"id":"030","key":"dice_total_7","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 일곱 칸!"},
    {"id":"031","key":"dice_total_8","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 여덟 칸!"},
    {"id":"032","key":"dice_total_9","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 아홉 칸!"},
    {"id":"033","key":"dice_total_10","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 열 칸!"},
    {"id":"034","key":"dice_total_11","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 열한 칸!"},
    {"id":"035","key":"dice_total_12","scene":"주사위 숫자 — 각각 따로 녹음","dir":"숫자를 분명하게","text":"합해서 열두 칸!"},
    {"id":"036","key":"move_01","scene":"이동 · 매입 · 건설","dir":"짧고 힘 있게","text":"출발!"},
    {"id":"037","key":"move_02","scene":"이동 · 매입 · 건설","dir":"기대하며","text":"새로운 도시가 기다리고 있어!"},
    {"id":"038","key":"arrival","scene":"이동 · 매입 · 건설","dir":"반갑게","text":"도착했어! 이곳을 둘러볼까?"},
    {"id":"039","key":"unowned_city","scene":"이동 · 매입 · 건설","dir":"제안하듯","text":"아직 주인이 없는 땅이야. 우리 도시로 만들어 볼까?"},
    {"id":"040","key":"buy_01","scene":"이동 · 매입 · 건설","dir":"기쁘게","text":"매입 완료! 이제 우리 땅이야!"},
    {"id":"041","key":"buy_02","scene":"이동 · 매입 · 건설","dir":"뿌듯하게","text":"새로운 도시의 주인이 됐어!"},
    {"id":"042","key":"buy_03","scene":"이동 · 매입 · 건설","dir":"설레게","text":"여기에 멋진 도시를 만들어 보자!"},
    {"id":"043","key":"build","scene":"이동 · 매입 · 건설","dir":"활기차게","text":"건설 시작! 도시가 자라나고 있어!"},
    {"id":"044","key":"building_complete","scene":"이동 · 매입 · 건설","dir":"밝게","text":"짠! 새 건물이 완성됐어!"},
    {"id":"045","key":"hotel_complete","scene":"이동 · 매입 · 건설","dir":"감탄하며","text":"호텔 완성! 도시가 더욱 근사해졌어!"},
    {"id":"046","key":"own_city","scene":"이동 · 매입 · 건설","dir":"따뜻하게","text":"우리 도시에 돌아왔네!"},
    {"id":"047","key":"opponent_city","scene":"이동 · 매입 · 건설","dir":"차분하게","text":"다른 친구의 땅이야. 통행료를 확인해 줘."},
    {"id":"048","key":"toll_received","scene":"이동 · 매입 · 건설","dir":"짧고 기쁘게","text":"통행료가 들어왔어!"},
    {"id":"049","key":"toll_paid","scene":"이동 · 매입 · 건설","dir":"가볍게","text":"통행료를 냈어. 다음 기회를 노려 보자!"},
    {"id":"050","key":"insufficient_money","scene":"이동 · 매입 · 건설","dir":"부드럽게","text":"돈이 조금 부족해. 다른 작전을 생각해 볼까?"},
    {"id":"051","key":"city_hanbat","scene":"도시 도착 안내","dir":"지명을 또렷하게","text":"한밭수목원에 도착했어! 초록 정원을 둘러보자."},
    {"id":"052","key":"city_expo","scene":"도시 도착 안내","dir":"지명을 또렷하게","text":"엑스포공원이야! 멋진 한빛탑이 보이네."},
    {"id":"053","key":"city_yuseong","scene":"도시 도착 안내","dir":"편안하게","text":"유성온천에 도착했어! 따뜻한 온천에서 쉬어 갈까?"},
    {"id":"054","key":"city_jangtaesan","scene":"도시 도착 안내","dir":"반갑게","text":"장태산이야! 높이 솟은 나무들이 반겨 주네."},
    {"id":"055","key":"city_sungsimdang","scene":"도시 도착 안내","dir":"기분 좋게","text":"성심당에 도착했어! 고소한 빵 냄새가 나는 것 같아."},
    {"id":"056","key":"city_hyangjeoksan","scene":"도시 도착 안내","dir":"산뜻하게","text":"향적산이야! 푸른 산길을 함께 걸어 보자."},
    {"id":"057","key":"city_sindoan","scene":"도시 도착 안내","dir":"편안하게","text":"신도안에 도착했어! 산자락 풍경이 참 평화롭네."},
    {"id":"058","key":"city_sagye","scene":"도시 도착 안내","dir":"따뜻하게","text":"사계고택이야! 고즈넉한 한옥이 기다리고 있어."},
    {"id":"059","key":"city_gyeryong_thesharp","scene":"도시 도착 안내","dir":"반갑게","text":"계룡더샵에 도착했어! 새로운 도시 풍경이 펼쳐지네."},
    {"id":"060","key":"city_gyeryongdae","scene":"도시 도착 안내","dir":"차분하게","text":"계룡대에 도착했어! 주변의 산들이 든든하게 둘러싸고 있네."},
    {"id":"061","key":"city_gyeryongsan","scene":"도시 도착 안내","dir":"감탄하며","text":"계룡산이야! 웅장한 산봉우리가 보인다!"},
    {"id":"062","key":"city_donam","scene":"도시 도착 안내","dir":"다정하게","text":"돈암서원에 도착했어! 옛 배움터를 둘러보자."},
    {"id":"063","key":"city_ganggyeong","scene":"도시 도착 안내","dir":"호기심 있게","text":"강경거리야! 오래된 골목에서 이야기를 찾아볼까?"},
    {"id":"064","key":"city_tapjeong","scene":"도시 도착 안내","dir":"감탄하며","text":"탑정호에 도착했어! 호수 위의 다리가 멋지네."},
    {"id":"065","key":"city_gwanchoksa","scene":"도시 도착 안내","dir":"반갑게","text":"관촉사야! 커다란 석불이 우리를 반겨 주네."},
    {"id":"066","key":"city_insadong","scene":"도시 도착 안내","dir":"설레게","text":"인사동에 도착했어! 골목마다 멋진 작품이 가득해."},
    {"id":"067","key":"city_dongdaemun","scene":"도시 도착 안내","dir":"활기차게","text":"동대문이야! 커다란 성문을 구경해 보자."},
    {"id":"068","key":"city_maumhwabun","scene":"도시 도착 안내","dir":"이름 중간에 짧게 호흡","text":"북촌한옥마을 마음화분에 도착했어! 예쁜 화분들이 반겨 주네."},
    {"id":"069","key":"city_banpo","scene":"도시 도착 안내","dir":"부드럽게","text":"반포한강이야! 강바람과 반짝이는 물빛을 느껴 봐."},
    {"id":"070","key":"city_namsan","scene":"도시 도착 안내","dir":"감탄하며","text":"남산타워에 도착했어! 서울이 한눈에 보이네!"},
    {"id":"071","key":"city_gyeongbokgung","scene":"도시 도착 안내","dir":"설레게","text":"경복궁이야! 멋진 궁궐 여행을 시작해 보자."},
    {"id":"072","key":"item_get_01","scene":"아이템 · 주사위 강화 · 공격","dir":"놀라며","text":"반짝! 새 아이템을 얻었어!"},
    {"id":"073","key":"item_get_02","scene":"아이템 · 주사위 강화 · 공격","dir":"호기심 있게","text":"어떤 힘이 숨어 있을까?"},
    {"id":"074","key":"item_use","scene":"아이템 · 주사위 강화 · 공격","dir":"힘 있게","text":"아이템의 힘을 보여 줘!"},
    {"id":"075","key":"dice_crystal","scene":"아이템 · 주사위 강화 · 공격","dir":"기쁘게","text":"주사위 강화 재료를 발견했어!"},
    {"id":"076","key":"dice_upgrade","scene":"아이템 · 주사위 강화 · 공격","dir":"뿌듯하게","text":"강화 성공! 주사위가 더 강해졌어!"},
    {"id":"077","key":"dice_rush","scene":"아이템 · 주사위 강화 · 공격","dir":"빠르고 활기차게","text":"질주 주사위! 힘차게 굴려 보자!"},
    {"id":"078","key":"dice_steady","scene":"아이템 · 주사위 강화 · 공격","dir":"자신 있게","text":"정밀 주사위! 침착하게 기회를 잡아 봐."},
    {"id":"079","key":"dice_lucky","scene":"아이템 · 주사위 강화 · 공격","dir":"설레게","text":"행운 주사위! 좋은 일이 생길 것 같아!"},
    {"id":"080","key":"attack","scene":"아이템 · 주사위 강화 · 공격","dir":"짧고 강하게","text":"지금이 기회야! 공격!"},
    {"id":"081","key":"attack_success","scene":"아이템 · 주사위 강화 · 공격","dir":"통쾌하게","text":"성공! 멋진 한 수였어!"},
    {"id":"082","key":"defend","scene":"아이템 · 주사위 강화 · 공격","dir":"단단하게","text":"방어! 우리 도시를 지켜 줘!"},
    {"id":"083","key":"defend_success","scene":"아이템 · 주사위 강화 · 공격","dir":"안도하며","text":"막아냈어! 든든한 방어였어!"},
    {"id":"084","key":"comeback","scene":"아이템 · 주사위 강화 · 공격","dir":"응원하며","text":"아직 끝나지 않았어. 역전의 기회를 잡아 봐!"},
    {"id":"085","key":"team_start","scene":"팀전 · 결과 · 연결 안내","dir":"힘차게","text":"함께하면 더 강해져! 우리 팀, 출발!"},
    {"id":"086","key":"ally_city","scene":"팀전 · 결과 · 연결 안내","dir":"따뜻하게","text":"우리 팀의 도시야! 반가운 곳에 도착했네."},
    {"id":"087","key":"ally_help","scene":"팀전 · 결과 · 연결 안내","dir":"기쁘게","text":"든든한 팀워크야!"},
    {"id":"088","key":"victory_01","scene":"팀전 · 결과 · 연결 안내","dir":"환호하며","text":"승리! 멋진 도시를 만들어 냈어!"},
    {"id":"089","key":"victory_02","scene":"팀전 · 결과 · 연결 안내","dir":"축하하며","text":"오늘의 도시 왕은 바로 너야!"},
    {"id":"090","key":"team_victory","scene":"팀전 · 결과 · 연결 안내","dir":"함께 환호하듯","text":"우리 팀이 승리했어! 최고의 팀워크였어!"},
    {"id":"091","key":"defeat","scene":"팀전 · 결과 · 연결 안내","dir":"다정하게","text":"아쉽지만 멋진 모험이었어. 다음엔 승리를 노려 보자!"},
    {"id":"092","key":"game_end","scene":"팀전 · 결과 · 연결 안내","dir":"따뜻하게","text":"함께해서 즐거웠어! 다음 여행에서 또 만나!"},
    {"id":"093","key":"reconnecting","scene":"팀전 · 결과 · 연결 안내","dir":"차분하게","text":"연결을 확인하고 있어. 잠시만 기다려 줘."},
    {"id":"094","key":"reconnected","scene":"팀전 · 결과 · 연결 안내","dir":"안도하며","text":"다시 연결됐어! 모험을 이어 가자."},
    {"id":"095","key":"room_full","scene":"팀전 · 결과 · 연결 안내","dir":"부드럽게","text":"지금은 방이 가득 찼어. 새 방에서 만나자!"},
    {"id":"096","key":"waiting_host","scene":"팀전 · 결과 · 연결 안내","dir":"기대하며","text":"모두 모였어! 방장이 시작하면 출발할 거야."},
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = LINES;
  else root.CITY_LINES = LINES;
})(typeof window !== "undefined" ? window : globalThis);
